# permissions for end users to edit heatapis.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: heatapi-editor-role
rules:
- apiGroups:
  - heat.openstack.org
  resources:
  - heatapis
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - heat.openstack.org
  resources:
  - heatapis/status
  verbs:
  - get
