# permissions for end users to view heatengines.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: heatengine-viewer-role
rules:
- apiGroups:
  - heat.openstack.org
  resources:
  - heatengines
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - heat.openstack.org
  resources:
  - heatengines/status
  verbs:
  - get
