# permissions for end users to view heatapis.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: heatapi-viewer-role
rules:
- apiGroups:
  - heat.openstack.org
  resources:
  - heatapis
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - heat.openstack.org
  resources:
  - heatapis/status
  verbs:
  - get
