---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  creationTimestamp: null
  name: manager-role
rules:
- apiGroups:
  - heat.openstack.org
  resources:
  - heatapis
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - heat.openstack.org
  resources:
  - heatapis/finalizers
  verbs:
  - update
- apiGroups:
  - heat.openstack.org
  resources:
  - heatapis/status
  verbs:
  - get
  - patch
  - update
- apiGroups:
  - heat.openstack.org
  resources:
  - heatengines
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - heat.openstack.org
  resources:
  - heatengines/finalizers
  verbs:
  - update
- apiGroups:
  - heat.openstack.org
  resources:
  - heatengines/status
  verbs:
  - get
  - patch
  - update
